// <auto-generated-like />
// Thin, modern .NET 10+ interop layer for the unified CNET native library.
// Uses LibraryImport for source generation, AOT-friendliness, and performance.
// Target: .NET 10 (or .NET 8/9 with LibraryImport available).
//
// Build the C library first:
//   make cnet_dll
// Then ensure cnet.dll (or cnet.so) is next to your app or in PATH / LD_LIBRARY_PATH.

using System;
using System.Linq;
using System.Text;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

namespace CNET.Cce.Interop;

internal static partial class CceNative
{
    // Unified superset library: CCE + certified CNET engine + soul host.
    // The compatibility cce library may still be built for native consumers,
    // but managed code has one source of native ABI truth.
    private const string LibraryName = "cnet";
    private const string CnetLibraryName = LibraryName;

    static CceNative()
    {
        // Improve P/Invoke reliability: try to load from locations next to this assembly,
        // the current directory, or the app context base directory.
        TryRegisterNativeLibraryResolver();
    }

    private static void TryRegisterNativeLibraryResolver()
    {
        try
        {
            string baseDir = System.AppContext.BaseDirectory;
            string currentDir = Environment.CurrentDirectory;

            // Common locations during development and after `dotnet build/test`
            string[] candidateDirs = {
                baseDir,
                currentDir,
                System.IO.Path.GetFullPath(System.IO.Path.Combine(baseDir, "..")),
                System.IO.Path.GetFullPath(System.IO.Path.Combine(currentDir, "..", "..", "..")),
            };

            foreach (string dir in candidateDirs.Distinct(StringComparer.OrdinalIgnoreCase))
            {
                if (string.IsNullOrEmpty(dir)) continue;

                // Unified CNET engine (CCE + soul_host + route/dag).
                string cnetDll = System.IO.Path.Combine(dir, "cnet.dll");
                string cnetSo = System.IO.Path.Combine(dir, "cnet.so");
                string cnetDylib = System.IO.Path.Combine(dir, "cnet.dylib");
                if (System.IO.File.Exists(cnetDll)) { System.Runtime.InteropServices.NativeLibrary.Load(cnetDll); return; }
                if (System.IO.File.Exists(cnetSo)) { System.Runtime.InteropServices.NativeLibrary.Load(cnetSo); return; }
                if (System.IO.File.Exists(cnetDylib)) { System.Runtime.InteropServices.NativeLibrary.Load(cnetDylib); return; }
            }

            // Last attempt: explicit load using full known location from repo root relative to current dir
            var possibleRootDll = System.IO.Path.GetFullPath(System.IO.Path.Combine(currentDir, "..", "..", "..", "cnet.dll"));
            if (System.IO.File.Exists(possibleRootDll))
            {
                System.Runtime.InteropServices.NativeLibrary.Load(possibleRootDll);
            }
        }
        catch
        {
            // Let the normal P/Invoke search continue
        }
    }

    // ============================================
    // Enums (must match C)
    // ============================================

    internal enum CceResult : int
    {
        Ok = 0,
        ErrOom = -1,
        ErrInvalidArg = -2,
        ErrIo = -3,
        ErrNotFound = -4,
        ErrFrozen = -5,
        ErrUnsupported = -6,
    }

    internal enum CceDiffMode : int
    {
        Local = 0,
        Hybrid = 1,
        Exact = 2,
    }

    internal enum CceSchedType : int
    {
        Cosine = 0,
        Warmup = 1,
        Plateau = 2,
        Step = 3,
    }

    // ============================================
    // Native structs (exact layout match)
    // ============================================

    [StructLayout(LayoutKind.Sequential)]
    internal struct CceBatchNative
    {
        public IntPtr Inputs;     // float*
        public IntPtr Targets;    // float*
        public nuint BatchSize;
        public nuint InDim;
        public nuint OutDim;
        public nuint Index;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct CceSchedulerNative
    {
        public CceSchedType Type;
        public float InitialLr;
        public int WarmupEpochs;
        public float DecayFactor;
        public int StepSize;
        public float PlateauFactor;
        public int PlateauPatience;
        // internal
        public float CurrentLr;
        public float BestLoss;
        public int PatienceCounter;
        public int TotalSteps;
    }

    // ============================================
    // Model
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_model_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelCreate(out IntPtr model, [MarshalAs(UnmanagedType.LPStr)] string name);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceModelDestroy(IntPtr model);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_add_forest")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelAddForest(IntPtr model, IntPtr forest, [MarshalAs(UnmanagedType.LPStr)] string name);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_scheduler")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetScheduler(IntPtr model, IntPtr scheduler);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_diff_mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetDiffMode(IntPtr model, CceDiffMode mode);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_train")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial double CceModelTrain(IntPtr model, IntPtr dataset, nuint maxEpochs, float targetLoss);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_train_batch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial double CceModelTrainBatch(IntPtr model, ref CceBatchNative batch);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_infer_batch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelInferBatch(IntPtr model, ref CceBatchNative batch, int[] outLabels, float[] confs);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_forward")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelForward(IntPtr model, float[] input, int inDim, float[] output, int outputCap, out int outDim);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_forward_batch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelForwardBatch(IntPtr model, ref CceBatchNative batch, float[] outputs, int outputCapPerSample, out int outDim);

    // Single infer (existing)
    [LibraryImport(LibraryName, EntryPoint = "cce_model_infer")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelInfer(IntPtr model, float[] input, int dim, out int outLabel, out float conf);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_loss")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetLoss(IntPtr model, int classify);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_learn_params")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetLearnParams(IntPtr model, float goodness, float dfa, float gradClip);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_use_autograd")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetUseAutograd(IntPtr model, int use);

    // GPU (optional acceleration for training loops on CUDA-capable builds)
    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_gpu")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetGpu(IntPtr model, IntPtr gpuCtx);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_set_gpu_owned")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSetGpuOwned(IntPtr model, IntPtr gpuCtx);

    // Low-level GPU context creation (for advanced users or when CceModel.UseDevice is not enough)
    [LibraryImport(LibraryName, EntryPoint = "cce_gpu_init_cuda")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceGpuInitCuda(out IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_gpu_init")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceGpuInit(out IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_gpu_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceGpuDestroy(IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_gpu_is_cuda")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceGpuIsCuda(IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_save")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelSave(IntPtr model, [MarshalAs(UnmanagedType.LPStr)] string path);

    [LibraryImport(LibraryName, EntryPoint = "cce_model_load")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceModelLoad(IntPtr model, [MarshalAs(UnmanagedType.LPStr)] string path);

    // ============================================
    // Forest (model-definition / composition)
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_open")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestOpen(out IntPtr forest, [MarshalAs(UnmanagedType.LPStr)] string archivePath, int maxBranches);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_close")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceForestClose(IntPtr forest);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_connect")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestConnect(IntPtr forest, int fromIdx, int toIdx, int connType);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_merge")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceForestMerge(IntPtr dst, IntPtr src, [MarshalAs(UnmanagedType.LPStr)] string namePrefix);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_set_diff_mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestSetDiffMode(IntPtr forest, CceDiffMode mode);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_set_branch_diff_mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestSetBranchDiffMode(IntPtr forest, int branchIdx, CceDiffMode mode);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_set_branch_exact_tail_length")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestSetBranchExactTailLength(IntPtr forest, int branchIdx, int length);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_branch_count")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceForestBranchCount(IntPtr forest);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_branch_name")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestBranchName(IntPtr forest, int idx, byte[] buf, int len);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_seal")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestSeal(IntPtr forest);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_forward")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestForward(IntPtr forest, int branchIdx, float[] input, int inDim, float[] output, int outCap, out int actualOutDim);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_set_branch_linear_weights")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestSetBranchLinearWeights(IntPtr forest, int branchIdx,
        float[] weights, int wInDim, int wOutDim, float[] bias, int bDim);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_get_connections")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestGetConnections(IntPtr forest, int branchIdx, byte[] names, int[] types, ref int num, int maxConn);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_get_branch_blocks")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestGetBranchBlocks(
        IntPtr forest,
        int branchIdx,
        int[] types,
        int[] inputDims,
        int[] outputDims,
        ref int num,
        int maxBlocks);

    [LibraryImport(LibraryName, EntryPoint = "cce_cascade_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceCascadeCreate(out IntPtr cascade, int maxBlocks);

    [LibraryImport(LibraryName, EntryPoint = "cce_cascade_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceCascadeDestroy(IntPtr cascade);

    [LibraryImport(LibraryName, EntryPoint = "cce_cascade_add_linear")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceCascadeAddLinear(IntPtr cascade, int inputDim, int outputDim, float initScale);

    [LibraryImport(LibraryName, EntryPoint = "cce_cascade_add_linear_head")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceCascadeAddLinearHead(IntPtr cascade, int inputDim, int outputDim, float initScale);

    [LibraryImport(LibraryName, EntryPoint = "cce_cascade_add_patch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceCascadeAddPatch(IntPtr cascade, int patchSize, int stride, int channels);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_add_cascade_branch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestAddCascadeBranch(
        IntPtr forest,
        IntPtr cascade,
        [MarshalAs(UnmanagedType.LPStr)] string name,
        out int outBranchIdx);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_add_linear_branch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestAddLinearBranch(
        IntPtr forest,
        [MarshalAs(UnmanagedType.LPStr)] string name,
        int inputDim,
        int hiddenDim,
        int outputDim,
        float initScale,
        out int outBranchIdx);

    [LibraryImport(LibraryName, EntryPoint = "cce_forest_add_patch_branch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceForestAddPatchBranch(
        IntPtr forest,
        [MarshalAs(UnmanagedType.LPStr)] string name,
        int patchSize,
        int stride,
        int channels,
        int hiddenDim,
        int outputDim,
        float initScale,
        out int outBranchIdx);

    // ============================================
    // Dataset
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_from_arrays")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceDatasetFromArrays(
        out IntPtr ds,
        float[] inputs,
        float[] targets,
        nuint nSamples,
        nuint inDim,
        nuint outDim,
        nuint batchSize);

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_wrap_arrays")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceDatasetWrapArrays(
        out IntPtr ds,
        float[] inputs,
        float[] targets,
        nuint nSamples,
        nuint inDim,
        nuint outDim,
        nuint batchSize);

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_next_batch")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceDatasetNextBatch(IntPtr ds, ref CceBatchNative batch);

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_reset")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceDatasetReset(IntPtr ds);

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceDatasetDestroy(IntPtr ds);

    [LibraryImport(LibraryName, EntryPoint = "cce_dataset_shuffle")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceDatasetShuffle(IntPtr ds);

    // ============================================
    // Scheduler
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_scheduler_init")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceSchedulerInit(IntPtr scheduler, CceSchedType type, float initialLr);

    [LibraryImport(LibraryName, EntryPoint = "cce_scheduler_get_lr")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial float CceSchedulerGetLr(IntPtr scheduler, int epoch, float currentLoss);

    // ============================================
    // Low-level handle (for online adapt / cce_open)
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_open")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceOpen(out IntPtr handle, [MarshalAs(UnmanagedType.LPStr)] string archivePath);

    [LibraryImport(LibraryName, EntryPoint = "cce_close")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceClose(IntPtr handle);

    [LibraryImport(LibraryName, EntryPoint = "cce_infer")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceInfer(IntPtr handle, float[] input, int dim, out int outLabel, out float conf);

    [LibraryImport(LibraryName, EntryPoint = "cce_adapt")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceAdapt(IntPtr handle, float[] input, int dim, int label, float lr);

    [LibraryImport(LibraryName, EntryPoint = "cce_set_diff_mode")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceSetDiffMode(IntPtr handle, CceDiffMode mode);

    [LibraryImport(LibraryName, EntryPoint = "cce_set_scheduler")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceSetScheduler(IntPtr handle, IntPtr scheduler);

    // Helper to load a native scheduler state (used internally by high-level wrappers)
    internal static void InitScheduler(IntPtr sched, CceSchedType type, float lr)
    {
        CceSchedulerInit(sched, type, lr);
    }

    // === Autograd (raw returns to satisfy LibraryImport generator) ===
    [LibraryImport(LibraryName, EntryPoint = "cce_ag_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgCreateRaw(out IntPtr ctx, nuint maxNodes);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceAgDestroy(IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_zero_grad")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void CceAgZeroGrad(IntPtr ctx);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_backward")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgBackwardRaw(IntPtr ctx, IntPtr loss);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_tensor_from_array")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgTensorFromArrayRaw(IntPtr ctx, float[] data, int rows, int cols, int requiresGrad, out IntPtr tensor);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_data")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial IntPtr CceAgData(IntPtr tensor);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_grad")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial IntPtr CceAgGrad(IntPtr tensor);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_matmul")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgMatmulRaw(IntPtr ctx, IntPtr a, IntPtr b, out IntPtr @out);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_add_bias")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgAddBiasRaw(IntPtr ctx, IntPtr x, IntPtr bias, out IntPtr @out);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_relu")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgReluRaw(IntPtr ctx, IntPtr x, out IntPtr @out);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_mse_loss")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgMseLossRaw(IntPtr ctx, IntPtr pred, IntPtr target, out IntPtr loss);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_softmax_cross_entropy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgSoftmaxCrossEntropyRaw(IntPtr ctx, IntPtr logits, IntPtr target, out IntPtr loss);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_sgd_step")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgSgdStepRaw(IntPtr parameters, nuint count, float lr);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_exp")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgExpRaw(IntPtr ctx, IntPtr x, out IntPtr y);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_log")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgLogRaw(IntPtr ctx, IntPtr x, out IntPtr y);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_adam_step")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgAdamStepRaw(IntPtr parameters, nuint count, float lr, float beta1, float beta2, float eps, int t);

    [LibraryImport(LibraryName, EntryPoint = "cce_ag_set_gpu")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CceAgSetGpuRaw(IntPtr ctx, IntPtr gpuCtx);

    // ============================================
    // CCE Router (for routing specialists in perceptual + composition)
    // ============================================

    [StructLayout(LayoutKind.Sequential)]
    internal struct CceRouterNative
    {
        public float temperature;
        public float novelty_threshold;
        public int top_k;
    }

    [LibraryImport(LibraryName, EntryPoint = "cce_router_init")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceRouterInit(ref CceRouterNative r, float temp, int topK);

    [LibraryImport(LibraryName, EntryPoint = "cce_router_route")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceRouterRoute(ref CceRouterNative r, IntPtr forest,
        float[] input, int dim, out int topBranch, out float score);

    // ============================================
    // Perceptual leaves (glyph, 7seg, grid, block) + Glyph habitat integration
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptualCreate(out IntPtr forest, ref CceRouterNative router,
        int inputDim, int numClasses, [MarshalAs(UnmanagedType.LPStr)] string domainPrefix,
        int maxBranches, CceDiffMode diffMode);

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_train")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptualTrain(IntPtr forest, int inputDim);

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_forward")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptualForward(IntPtr forest, ref CceRouterNative router,
        float[] input, int dim,
        float[] outOnehot, int outDim,
        out float routerScore, out float branchGoodness,
        out int bestClass,
        float[] evidenceOut, int topk);

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_effective_margin")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial float CcePerceptualEffectiveMargin(float baseMargin, float routerScore, float branchGoodness);

    // 7seg convenience
    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_7seg_create")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptual7segCreate(out IntPtr forest, ref CceRouterNative router, int maxBranches);

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_7seg_train")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptual7segTrain(IntPtr forest);

    [LibraryImport(LibraryName, EntryPoint = "cce_perceptual_7seg_forward")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int CcePerceptual7segForward(IntPtr forest, ref CceRouterNative router,
        float[] input, int dim, float[] outOnehot, int outDim,
        out float routerScore, out float branchGoodness, out int bestClass,
        float[] evidenceOut, int topk);

    // ============================================
    // Supra extended (packed 1.6-bit + forest exposure for Router/Planner/Contracts/Perceptual/Glyph composition)
    // ============================================

    [LibraryImport(LibraryName, EntryPoint = "cce_supra_a2a_get_forest")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial IntPtr CceSupraA2aGetForest(IntPtr a2aHandle);

    [LibraryImport(LibraryName, EntryPoint = "cce_supra_a2a_load_packed")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial CceResult CceSupraA2aLoadPacked(out IntPtr handle, [MarshalAs(UnmanagedType.LPStr)] string packedPath);


    // ============================================
    // Deeper marshaling for high-level Router/Planner/Contracts (PrimitiveRegistry, Contract, planning)
    // Ports + Contracts for verifiable composition. BTN/CCE specialists can be registered.
    // ============================================


    // Note: full DagPlan etc require more handles; use for registration + named dispatch first.

    // ============================================
    // Soul host shim (CNET certified engine reachability)
    // Load .cnb base + optional model, run named units, route goals.
    // Mirrors usage in tests/soul_query.c + route_execute / dag_execute.
    // ============================================

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_open")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulOpen([MarshalAs(UnmanagedType.LPStr)] string basePath,
        [MarshalAs(UnmanagedType.LPStr)] string? modelPath, out IntPtr hostOut);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_unit_count")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulUnitCount(IntPtr host);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_unit_name")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulUnitName(IntPtr host, int index,
        [Out] byte[] output, int outputCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_oracle_count")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulOracleCount(IntPtr host);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_oracle_name")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulOracleName(IntPtr host, int index,
        [Out] byte[] output, int outputCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_oracle_kind")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulOracleKind(IntPtr host, int index,
        [Out] byte[] output, int outputCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_oracle_identity")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulOracleIdentity(IntPtr host, int index,
        out ulong behaviorDigest, out ulong artifactDigest,
        out ulong contractDigest, out ulong configDigest,
        out ulong retrievalSnapshotDigest, out ulong toolchainDigest);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_unit_dims")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulUnitDims(IntPtr host, [MarshalAs(UnmanagedType.LPStr)] string name,
        out int inTotal, out int outTotal);

    // Returns the unit's true output size (>=0; > outCap means truncated), or <0 on error.
    [LibraryImport(CnetLibraryName, EntryPoint = "soul_run")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulRun(IntPtr host, [MarshalAs(UnmanagedType.LPStr)] string name,
        double[] input, double[] output, int outCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_route")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulRoute(IntPtr host, [MarshalAs(UnmanagedType.LPStr)] string goalTag,
        double[] input, int inCap, double[] output, int outCap);

    // Real Laplace-smoothed reliability x1000 (500 = 0.5), <0 if not found.
    [LibraryImport(CnetLibraryName, EntryPoint = "soul_unit_reliability_milli")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulUnitReliabilityMilli(IntPtr host, [MarshalAs(UnmanagedType.LPStr)] string name);

    // Runtime health tick: one specialist_health_pass over the live registry
    // with the base as the contract source. Fills up to 13 counts; returns
    // the number written, or <0.
    [LibraryImport(CnetLibraryName, EntryPoint = "soul_health_tick")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulHealthTick(IntPtr host, [Out] long[] counts, int countsCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_unit_axes")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulUnitAxes(IntPtr host, [MarshalAs(UnmanagedType.LPStr)] string name,
        out int trust, out int role);

    // Explicit-signature request: served (>=0 = out_total, 0 = probe ok),
    // -3 = no plan (novel goal noted to the gap inbox), other <0 = error.
    [LibraryImport(CnetLibraryName, EntryPoint = "soul_request")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int SoulRequest(IntPtr host,
        int inFamily, int inWidth, int inCount, [MarshalAs(UnmanagedType.LPStr)] string inTag,
        int goalFamily, int goalWidth, int goalCount, [MarshalAs(UnmanagedType.LPStr)] string goalTag,
        double[]? input, int inLen, [Out] double[]? output, int outCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "soul_close")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void SoulClose(IntPtr host);

    // MCP tools (file, calculator, memory) exposed from the C driver
    [LibraryImport(CnetLibraryName, EntryPoint = "port_contract_mcp_file_read")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int McpFileRead([MarshalAs(UnmanagedType.LPStr)] string path,
        byte[] contentOut, nuint cap, out int fromCache);

    [LibraryImport(CnetLibraryName, EntryPoint = "port_contract_mcp_calculator")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int McpCalculator([MarshalAs(UnmanagedType.LPStr)] string expr,
        byte[] resultOut, nuint cap, out int fromMem);

    [LibraryImport(CnetLibraryName, EntryPoint = "port_contract_mcp_web_search")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int McpWebSearch([MarshalAs(UnmanagedType.LPStr)] string query,
        byte[] resultsOut, nuint cap, out int fromCache);

    [LibraryImport(CnetLibraryName, EntryPoint = "mcp_memory_init")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int McpMemoryInit();

    [LibraryImport(CnetLibraryName, EntryPoint = "mcp_recall_fact")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial int McpRecallFact([MarshalAs(UnmanagedType.LPStr)] string query,
        byte[] outBuf, nuint bufCap);

    [LibraryImport(CnetLibraryName, EntryPoint = "mcp_memorize_fact")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial void McpMemorizeFact([MarshalAs(UnmanagedType.LPStr)] string query,
        [MarshalAs(UnmanagedType.LPStr)] string summary);

    // ---- QGKP native compression envelope (cce_qgkp.h) -------------------

    // cce_qgkp_metadata: matches C struct layout exactly.
    //   u64 flags | char[64] architecture | char[32] quantization |
    //   i32 n_layer | i32 hidden | i32 context_length | i32 reserved
    // Using DllImport (not LibraryImport) because ByValArray marshalling
    // is not supported by the source generator for embedded arrays.
    [StructLayout(LayoutKind.Sequential, Pack = 0)]
    internal struct CceQgkpMetadata
    {
        public ulong Flags;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] Architecture;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] Quantization;
        public int NLayer;
        public int Hidden;
        public int ContextLength;
        public int Reserved;
    }

    // cce_qgkp_info: matches C struct layout (with natural alignment).
    //   u32 version | (pad) | u64 header_bytes | u64 flags | u64 payload_bytes |
    //   u64 payload_hash | char[64] architecture | char[32] quantization |
    //   i32 n_layer | i32 hidden | i32 context_length
    [StructLayout(LayoutKind.Sequential, Pack = 0)]
    internal struct CceQgkpInfo
    {
        public uint Version;
        public uint _pad;
        public ulong HeaderBytes;
        public ulong Flags;
        public ulong PayloadBytes;
        public ulong PayloadHash;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] Architecture;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] Quantization;
        public int NLayer;
        public int Hidden;
        public int ContextLength;
    }

    [DllImport(CnetLibraryName, EntryPoint = "cce_qgkp_pack_gguf", CallingConvention = CallingConvention.Cdecl)]
    internal static extern int QgkpPackGguf(
        [MarshalAs(UnmanagedType.LPStr)] string ggufPath,
        [MarshalAs(UnmanagedType.LPStr)] string qgkpPath,
        ref CceQgkpMetadata meta);

    [DllImport(CnetLibraryName, EntryPoint = "cce_qgkp_inspect", CallingConvention = CallingConvention.Cdecl)]
    internal static extern int QgkpInspect(
        [MarshalAs(UnmanagedType.LPStr)] string qgkpPath,
        ref CceQgkpInfo info);

    [DllImport(CnetLibraryName, EntryPoint = "cce_qgkp_materialize_gguf", CallingConvention = CallingConvention.Cdecl)]
    internal static extern int QgkpMaterializeGguf(
        [MarshalAs(UnmanagedType.LPStr)] string qgkpPath,
        [MarshalAs(UnmanagedType.LPStr)] string ggufPath);

    // Core engine symbols are also exported from cnet lib for direct use:
    // cnb_load, cnb_load_registry, cnb_get_unit, registry_*, route_plan, route_execute,
    // dag_plan, dag_execute, btn_forward, etc. Add [LibraryImport(CnetLibraryName, ...)] as needed.
}
