// <auto-generated />
// Generated by tools/gen_json_toolcall_alphabet.py from config/json_toolcall_v0.json
// Do not edit by hand.
namespace CNET.Cce;

public static partial class JsonToolCall
{
    public const int FeatureCountGen = 18;
    public const int ToolCountGen = 8;
    public const string UnitNameGen = "json_toolcall_v1";
    public const string InputTagGen = "jtc_feat";
    public const string GoalTagGen = "json_tool";

    private static readonly string[] ToolNamesGen =
    {
        "calculator",
        "memory_store",
        "memory_recall",
        "file_read",
        "cnet_recall",
        "web_search",
        "wiki_lookup",
        "final"
    };

    private static readonly string[] FeatureNamesGen =
    {
        "calculator",
        "memory_store",
        "memory_recall",
        "file_read",
        "cnet_recall",
        "web_search",
        "wiki_lookup",
        "final",
        "expr",
        "key",
        "value",
        "query",
        "path",
        "cond",
        "current",
        "answer",
        "tool",
        "args"
    };

    private static readonly string[] ExampleJsonGen =
    {
        "{\"tool\":\"calculator\",\"args\":{\"expr\":\"23 * 19\"}}",
        "{\"tool\":\"memory_store\",\"args\":{\"key\":\"k\",\"value\":\"v\"}}",
        "{\"tool\":\"memory_recall\",\"args\":{\"query\":\"k\"}}",
        "{\"tool\":\"file_read\",\"args\":{\"path\":\"readme.txt\"}}",
        "{\"tool\":\"cnet_recall\",\"args\":{\"cond\":0,\"current\":1}}",
        "{\"tool\":\"web_search\",\"args\":{\"query\":\"CNET machine learning\"}}",
        "{\"tool\":\"wiki_lookup\",\"args\":{\"query\":\"Alan Turing\"}}",
        "{\"final\":\"done\",\"answer\":\"ok\"}"
    };
}
