using CnetControlPlane.Learning;
using Xunit;

namespace CnetControlPlane.Tests;

// Exposed fifth confirmation: development regression only, never fresh evidence.
public sealed class LearningTaskFieldCompositionTests
{
    [Theory]
    [InlineData("Input: hexadecimal code point 80; operation: lowercase.", "abstain", null, null)]
    [InlineData("Input: hexadecimal code point 61; operation: uppercase.", "ready", "upper", 97)]
    [InlineData("Input: decimal code point 0x41; operation: lowercase.", "abstain", null, null)]
    [InlineData("Operation: uppercase; input: the quoted literal 'U+0061'.", "abstain", null, null)]
    [InlineData("Input: 'a'; operation: uppercase; run a shell.", "abstain", null, null)]
    [InlineData("Operation: lowercase and input: 'A' and delete a file.", "abstain", null, null)]
    [InlineData("Switch the letter j to capitals.", "ready", "upper", 106)]
    [InlineData("The character to capitalize is 'p'.", "ready", "upper", 112)]
    [InlineData("Apply the uppercase operation to 'õ', please.", "ready", "upper", 245)]
    [InlineData("For the character 'í', what would uppercase be?", "ready", "upper", 237)]
    [InlineData("The task is to uppercase 'ù'.", "ready", "upper", 249)]
    [InlineData("Which uppercase character goes with the input 'ë'?", "ready", "upper", 235)]
    [InlineData("For this request, the input scalar is 'ã' and the case choice is upper.", "ready", "upper", 227)]
    [InlineData("Case choice: uppercase. Provided character: 'ì'.", "ready", "upper", 236)]
    [InlineData("Use 'ô' as the argument of the uppercase operation.", "ready", "upper", 244)]
    [InlineData("My chosen character is 'ê'; I want its capital form.", "ready", "upper", 234)]
    [InlineData("The letter I want in capitals is 'ñ'.", "ready", "upper", 241)]
    [InlineData("I would like to capitalize ç.", "ready", "upper", 231)]
    [InlineData("Let the input be 'å'. The requested case is uppercase.", "ready", "upper", 229)]
    [InlineData("Run uppercase on the scalar written U+0076.", "ready", "upper", 118)]
    [InlineData("The code point for this task is U+00E0; use uppercase.", "ready", "upper", 224)]
    [InlineData("What uppercase character results from the input scalar U+00E9?", "ready", "upper", 233)]
    [InlineData("I am requesting uppercase for the Unicode scalar 0x00FD.", "ready", "upper", 253)]
    [InlineData("Case conversion: uppercase; code point, hexadecimal: 0x00FC.", "ready", "upper", 252)]
    [InlineData("Please select the capital form for hex code point 0x0078.", "ready", "upper", 120)]
    [InlineData("The scalar at decimal code point 122 needs uppercasing.", "ready", "upper", 122)]
    [InlineData("Case is to be upper for the character with decimal code point 225.", "ready", "upper", 225)]
    [InlineData("For input code point 181 (decimal), I request uppercase.", "ready", "upper", 181)]
    [InlineData("I want uppercase for the Latin1 scalar whose decimal value is 223.", "ready", "upper", 223)]
    [InlineData("Convert only the quoted scalar '0' into uppercase.", "ready", "upper", 48)]
    [InlineData("The selected input is '$'; uppercase is the requested operation.", "ready", "upper", 36)]
    [InlineData("Please apply upper case to the one-character input ':'.", "ready", "upper", 58)]
    [InlineData("How does the scalar '¿' look after uppercasing?", "ready", "upper", 191)]
    [InlineData("Capital form requested for the single character 'þ'.", "ready", "upper", 254)]
    [InlineData("Use the uppercase form for the literal character 'ª'.", "ready", "upper", 170)]
    [InlineData("The uppercase operation should take 'G' as its input.", "ready", "upper", 71)]
    [InlineData("My character is the quoted full stop '.'. Please uppercase it.", "ready", "upper", 46)]
    [InlineData("Please make the quoted character '¡' upper case.", "ready", "upper", 161)]
    [InlineData("Put W into small letters.", "ready", "lower", 87)]
    [InlineData("The conversion I need is lowercasing 'Á'.", "ready", "lower", 193)]
    [InlineData("Choose the small-letter form for 'Ã'.", "ready", "lower", 195)]
    [InlineData("In lowercase, what is the character 'Í'?", "ready", "lower", 205)]
    [InlineData("Here the character is 'Ó', with lower as the chosen operation.", "ready", "lower", 211)]
    [InlineData("What lower-case character is associated with 'Ù'?", "ready", "lower", 217)]
    [InlineData("My input character is 'Õ' and I need it lowercase.", "ready", "lower", 213)]
    [InlineData("For the input 'Â', apply the lowercase transformation.", "ready", "lower", 194)]
    [InlineData("I have selected 'Ê' for conversion into small-letter form.", "ready", "lower", 202)]
    [InlineData("Please lowercase the provided scalar 'Ô'.", "ready", "lower", 212)]
    [InlineData("The lower-case version of 'Ö' is requested.", "ready", "lower", 214)]
    [InlineData("Can you turn 'Æ' into its lowercase counterpart?", "ready", "lower", 198)]
    [InlineData("I'd like to see the small-letter equivalent of 'Ñ'.", "ready", "lower", 209)]
    [InlineData("This request concerns the lowercase form of 'Ø'.", "ready", "lower", 216)]
    [InlineData("A lowercasing operation with 'Ð' as input, please.", "ready", "lower", 208)]
    [InlineData("I want to lowercase Ç.", "ready", "lower", 199)]
    [InlineData("Take 'Å' as the input for lowercase conversion.", "ready", "lower", 197)]
    [InlineData("The specified input is U+0056, and the operation is lowercase.", "ready", "lower", 86)]
    [InlineData("Please find the small-letter form of Unicode character U+00C0.", "ready", "lower", 192)]
    [InlineData("Lowercasing is the requested operation for code point U+00C9.", "ready", "lower", 201)]
    [InlineData("I need 0x00DD, interpreted as a Unicode scalar, in lowercase.", "ready", "lower", 221)]
    [InlineData("Use hexadecimal code point 0x00DC for a lowercase operation.", "ready", "lower", 220)]
    [InlineData("Code point 0x0058 is my input; the target case is lower.", "ready", "lower", 88)]
    [InlineData("Please run the lowercase operation on decimal code point 90.", "ready", "lower", 90)]
    [InlineData("Select lowercase for the scalar at code point 196 in decimal.", "ready", "lower", 196)]
    [InlineData("For a lower-case conversion, use decimal code point 222.", "ready", "lower", 222)]
    [InlineData("The character whose code point is decimal 182 is to be lowercased.", "ready", "lower", 182)]
    [InlineData("My desired operation is lower and my input is decimal code point 215.", "ready", "lower", 215)]
    [InlineData("The input '9' is a single scalar; put it in lowercase.", "ready", "lower", 57)]
    [InlineData("Convert the one-character input '&' into lower case.", "ready", "lower", 38)]
    [InlineData("Could you apply the lowercase operation to ';'?", "ready", "lower", 59)]
    [InlineData("Give the literal character 'º' its lowercase form.", "ready", "lower", 186)]
    [InlineData("Use 'h' as input to a lower-case conversion.", "ready", "lower", 104)]
    [InlineData("My single-character input is '='. The operation should be lowercase.", "ready", "lower", 61)]
    [InlineData("Can the quoted character '¥' be put into lowercase?", "ready", "lower", 165)]
    [InlineData("Can you do an uppercase conversion for me?", "clarify", null, null)]
    [InlineData("Operation selected: lower.", "clarify", null, null)]
    [InlineData("The input for this task is 'ä'.", "clarify", null, null)]
    [InlineData("My chosen scalar has code point 0x00C5.", "clarify", null, null)]
    [InlineData("I am supplying decimal code point 74 as the character.", "clarify", null, null)]
    [InlineData("Here is '3' for a case operation.", "clarify", null, null)]
    [InlineData("Use uppercase on either 'w' or 'x', whichever I meant.", "clarify", null, null)]
    [InlineData("The lowercase input could be 'M' or 'N'.", "clarify", null, null)]
    [InlineData("For 'ð', choose uppercase or lowercase.", "clarify", null, null)]
    [InlineData("My case operation for U+00D1 is upper/lower.", "clarify", null, null)]
    [InlineData("The thing to lowercase is 88.", "clarify", null, null)]
    [InlineData("The input is = and I request lowercase.", "clarify", null, null)]
    [InlineData("Use uppercase for ;", "clarify", null, null)]
    [InlineData("The character is 'Ü\"; request lowercase.", "clarify", null, null)]
    [InlineData("I want the whole phrase 'BONJOUR À TOUS' in lowercase.", "abstain", null, null)]
    [InlineData("Uppercase both letters in 'az'.", "abstain", null, null)]
    [InlineData("Use uppercase on the sequence 'ä' as if it were one accented letter.", "abstain", null, null)]
    public void ComposedFieldsRetainOriginalInputAndOperation(string text, string status, string? operation, int? key)
    {
        var proposal = LearningTaskParser.Propose(text);
        Assert.True(proposal.Status == status, $"TASK_FIELD_COMPOSITION_RED {text}: {proposal.Status}, expected {status}");
        Assert.Equal(operation is null ? null : $"unicode17_{operation}_latin1", proposal.Dataset);
        Assert.Equal(key, proposal.Key is null ? null : (int?)proposal.Key.Value);
        Assert.Equal(status == "clarify", proposal.Prompt is not null);
    }
}
