#!/usr/bin/env bash
# Deploy CNET-Minimal to this host and wire cnet-marble user units.
# Install root: ~/.local/share/cnet-minimal/current
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SHARE="${XDG_DATA_HOME:-$HOME/.local/share}/cnet-minimal"
VERSIONS="$SHARE/versions"
CURRENT="$SHARE/current"
VAR="$SHARE/var"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
DROPIN_EV="$UNIT_DIR/roe-evolve-tick.service.d"
DROPIN_AU="$UNIT_DIR/cnet-autonomous-cycle.service.d"
DROPIN_HE="$UNIT_DIR/cnet-marble-health.service.d"
BIN_LINK="${XDG_BIN_HOME:-$HOME/.local/bin}"

echo "=== CNET-Minimal deploy → $SHARE ==="

# Build/package if needed
if [[ ! -f dist/CNET-Minimal-latest.path ]] || [[ ! -d $(cat dist/CNET-Minimal-latest.path 2>/dev/null || echo /nope) ]]; then
  bash scripts/package_cnet_minimal.sh
fi
SRC=$(cat dist/CNET-Minimal-latest.path)
VER=$(basename "$SRC")
echo "source package=$SRC"

mkdir -p "$VERSIONS" "$VAR/logs" "$BIN_LINK" "$UNIT_DIR"
# Install versioned copy
DEST="$VERSIONS/$VER"
rm -rf "$DEST"
cp -a "$SRC" "$DEST"
ln -sfn "$DEST" "$CURRENT"

# Preserve / merge live miss_log + personal from previous current if any
if [[ -f $VAR/miss_log.jsonl ]]; then
  cp -a "$VAR/miss_log.jsonl" "$CURRENT/data/roe_daily_packs/miss_log.jsonl"
else
  # seed from repo traffic if present
  if [[ -f artifacts/roe_daily_packs/miss_log.jsonl ]]; then
    cp -a artifacts/roe_daily_packs/miss_log.jsonl "$VAR/miss_log.jsonl"
    cp -a "$VAR/miss_log.jsonl" "$CURRENT/data/roe_daily_packs/miss_log.jsonl"
  else
    : > "$VAR/miss_log.jsonl"
    : > "$CURRENT/data/roe_daily_packs/miss_log.jsonl"
  fi
fi
# Keep var/miss_log as canonical: bind into package packs
rm -f "$CURRENT/data/roe_daily_packs/miss_log.jsonl"
ln -sfn "$VAR/miss_log.jsonl" "$CURRENT/data/roe_daily_packs/miss_log.jsonl"

# Merge pack_personal from repo if package empty-ish
if [[ -d artifacts/roe_daily_packs/pack_personal/skills ]]; then
  mkdir -p "$CURRENT/data/roe_daily_packs/pack_personal"
  cp -a artifacts/roe_daily_packs/pack_personal/. "$CURRENT/data/roe_daily_packs/pack_personal/" 2>/dev/null || true
fi

# Gold from repo into live packs
if [[ -d artifacts/roe_daily_packs/gold ]]; then
  mkdir -p "$CURRENT/data/roe_daily_packs/gold"
  cp -a artifacts/roe_daily_packs/gold/. "$CURRENT/data/roe_daily_packs/gold/" 2>/dev/null || true
fi

# Env file for units + shell
ENVF="$SHARE/cnet-minimal.env"
cat > "$ENVF" <<EOF
# Generated by scripts/deploy_cnet_minimal.sh — do not put secrets here
CNET_MINIMAL_ROOT=$CURRENT
CNET_PACKS_ROOT=$CURRENT/data/roe_daily_packs
CNET_FRONT_DOOR_BIN=$CURRENT/bin/roe_front_door
CNET_BLOCKLIST=$CURRENT/config/promote_blocklist.txt
CNET_MISS_LOG=$VAR/miss_log.jsonl
PATH=$CURRENT/bin:\$PATH
EOF

# User bin wrappers
cat > "$BIN_LINK/cnet-ask" <<EOF
#!/usr/bin/env bash
set -euo pipefail
ROOT="$CURRENT"
Q="\${1:-}"
[[ -n "\$Q" ]] || { echo "usage: cnet-ask \\"query\\""; exit 2; }
exec "\$ROOT/bin/roe_front_door" ask "\$Q" --root "\$ROOT/data/roe_daily_packs"
EOF
chmod +x "$BIN_LINK/cnet-ask"
ln -sfn "$CURRENT/bin/roe_domain_route" "$BIN_LINK/roe_domain_route"
ln -sfn "$CURRENT/bin/roe_chain_think" "$BIN_LINK/roe_chain_think"

# Systemd drop-ins (EnvironmentFile)
for d in "$DROPIN_EV" "$DROPIN_AU" "$DROPIN_HE"; do
  mkdir -p "$d"
done
cat > "$DROPIN_EV/10-cnet-minimal.conf" <<EOF
[Service]
EnvironmentFile=-$ENVF
Environment=CNET_MINIMAL_ROOT=$CURRENT
Environment=CNET_PACKS_ROOT=$CURRENT/data/roe_daily_packs
Environment=CNET_FRONT_DOOR_BIN=$CURRENT/bin/roe_front_door
Environment=CNET_BLOCKLIST=$CURRENT/config/promote_blocklist.txt
# evolve still runs from repo tree (python tools); packs/front_door from package
EOF
cat > "$DROPIN_AU/10-cnet-minimal.conf" <<EOF
[Service]
EnvironmentFile=-$ENVF
Environment=CNET_MINIMAL_ROOT=$CURRENT
Environment=CNET_PACKS_ROOT=$CURRENT/data/roe_daily_packs
Environment=CNET_FRONT_DOOR_BIN=$CURRENT/bin/roe_front_door
Environment=CNET_BLOCKLIST=$CURRENT/config/promote_blocklist.txt
EOF
cat > "$DROPIN_HE/10-cnet-minimal.conf" <<EOF
[Service]
EnvironmentFile=-$ENVF
Environment=CNET_MINIMAL_ROOT=$CURRENT
EOF

# Also install unit sources from repo if missing
cp -a scripts/systemd/cnet-marble.target "$UNIT_DIR/" 2>/dev/null || true
cp -a scripts/systemd/roe-evolve-tick.* "$UNIT_DIR/" 2>/dev/null || true
cp -a scripts/systemd/cnet-autonomous-cycle.* "$UNIT_DIR/" 2>/dev/null || true
cp -a scripts/systemd/cnet-marble-health.* "$UNIT_DIR/" 2>/dev/null || true

systemctl --user daemon-reload
systemctl --user enable cnet-marble.target roe-evolve-tick.timer cnet-autonomous-cycle.timer cnet-marble-health.timer 2>/dev/null || true
systemctl --user restart roe-evolve-tick.timer cnet-autonomous-cycle.timer cnet-marble-health.timer 2>/dev/null || true
systemctl --user start cnet-marble.target 2>/dev/null || true

# In-place smoke under deploy path
export CNET_MINIMAL_ROOT="$CURRENT"
export CNET_PACKS_ROOT="$CURRENT/data/roe_daily_packs"
export CNET_FRONT_DOOR_BIN="$CURRENT/bin/roe_front_door"
echo "---- deploy smoke ----"
CNET_MINIMAL_ROOT="$CURRENT" bash "$CURRENT/scripts/cnet_runtime_smoke.sh" | tee "$VAR/logs/deploy_smoke.log"
grep -q CNET_RUNTIME_SMOKE_PASS "$VAR/logs/deploy_smoke.log"

# Live traffic probe → miss_log
echo "---- live ask (logs miss on OOD) ----"
"$BIN_LINK/cnet-ask" "who are you" | head -15 | tee -a "$VAR/logs/deploy_ask.log"
"$BIN_LINK/cnet-ask" "format-truncation werror" | head -10 | tee -a "$VAR/logs/deploy_ask.log"
# OOD should append miss eventually via front door or we log
"$CURRENT/bin/roe_front_door" ask "deploy probe unique xyzzy-$(date +%s)" --root "$CURRENT/data/roe_daily_packs" 2>&1 | tee -a "$VAR/logs/deploy_ask.log" | tail -8 || true

echo "miss_log lines: $(wc -l < "$VAR/miss_log.jsonl" || echo 0)"
echo "CURRENT=$CURRENT"
echo "ENV=$ENVF"
systemctl --user is-active cnet-marble.target roe-evolve-tick.timer cnet-autonomous-cycle.timer || true
systemctl --user show roe-evolve-tick.service -p Environment --no-pager 2>/dev/null | head -5 || true
echo "CNET_MINIMAL_DEPLOY_PASS"
