#!/usr/bin/env bash
# Generated claims ledger: read the gate logs, verify each positive marker,
# and emit machine-readable records + a generated table. The point is that
# "Verified Today" becomes derivable from evidence on disk instead of prose:
# a gate that never ran, was renamed, or regressed shows up as MISSING/FAIL
# here even if the README still says otherwise.
#
# Outputs:
#   logs/claims.jsonl                 one JSON record per claim
#   docs/verified-today.generated.md  human-readable table
set -u
cd "$(dirname "$0")/.."

HOST="$(uname -n) $(uname -sr)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
JSONL="logs/claims.jsonl"
MD="docs/verified-today.generated.md"
mkdir -p logs docs

# claim id | gate log | required marker
CLAIMS='
unified_adapter|logs/unified_adapter.log|UNIFIED_ADAPTER_PASS
unified_cce_adapter|logs/unified_cce_adapter.log|UNIFIED_CCE_ADAPTER_PASS
unified_oracle_adapter|logs/unified_oracle_adapter.log|ORACLE_CONTRACT_ADAPTER_PASS
unified_specialist_het_plan|logs/unified_specialist.log|HET_PLAN_PASS
oracle_v2|logs/oracle_v2_test.log|ORACLE_V2_PASS
async_runtime|logs/unified_async.log|ASYNC_RUNTIME_PASS
async_gpu_lanes|logs/unified_gpu.log|ASYNC_GPU_LANES_PASS
qgkp_envelope|logs/qgkp_envelope_test.log|QGKP_ENVELOPE_PASS
model_runtime|logs/unified_models_runtime.log|MODEL_RUNTIME_PASS
model_catalog|logs/unified_models_catalog.log|MODEL_CATALOG_PASS
ds4_dual_launcher|logs/unified_ds4_launcher.log|DS4_DUAL_LAUNCHER_PASS
soul_host|logs/soul_host_test.log|SOUL_HOST_UNIFIED_PASS
dotnet_host|logs/unified_host.log|CNET_HOST_UNIFIED_PASS
'

: > "$JSONL"
{
  echo "# Verified Today (generated)"
  echo
  echo "Generated by \`make claims\` at $NOW on \`$HOST\`."
  echo "Do not edit; regenerate. A FAIL/MISSING row here outranks any prose claim."
  echo
  echo "| Claim | Gate log | Marker | Verdict | Log time (UTC) |"
  echo "|---|---|---|---|---|"
} > "$MD"

total=0 passed=0
while IFS='|' read -r id log marker; do
  [ -z "$id" ] && continue
  total=$((total + 1))
  if [ ! -f "$log" ]; then
    verdict="MISSING"; ts="-"
  elif grep -qF "$marker" "$log"; then
    verdict="PASS"; passed=$((passed + 1))
    ts="$(date -u -r "$log" +%Y-%m-%dT%H:%M:%SZ)"
  else
    verdict="FAIL"
    ts="$(date -u -r "$log" +%Y-%m-%dT%H:%M:%SZ)"
  fi
  printf '{"claim":"%s","gate_log":"%s","marker":"%s","verdict":"%s","log_utc":"%s","generated_utc":"%s","host":"%s"}\n' \
    "$id" "$log" "$marker" "$verdict" "$ts" "$NOW" "$HOST" >> "$JSONL"
  printf '| %s | `%s` | `%s` | %s | %s |\n' "$id" "$log" "$marker" "$verdict" "$ts" >> "$MD"
done <<EOF
$CLAIMS
EOF

{
  echo
  echo "**$passed/$total claims verified.** MISSING means the gate has not run"
  echo "on this checkout (evidence absent, claim unproven — not a failure)."
} >> "$MD"

echo "claims: $passed/$total verified -> $JSONL, $MD"
