#!/usr/bin/env bash
# Generate a machine-readable claims ledger from gate logs.
#
# Default mode reports all evidence on disk. --strict makes any required
# MISSING/FAIL/STALE verdict fatal. --scope limits the required denominator;
# out-of-scope claims remain visible instead of being silently omitted.
set -u
cd "$(dirname "$0")/.."

STRICT=0
SCOPE="all"
SINCE=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --strict)
      STRICT=1
      shift
      ;;
    --scope)
      [ "$#" -ge 2 ] || { echo "claims: --scope requires a value" >&2; exit 2; }
      SCOPE="$2"
      shift 2
      ;;
    --since)
      [ "$#" -ge 2 ] || { echo "claims: --since requires a path" >&2; exit 2; }
      SINCE="$2"
      shift 2
      ;;
    *)
      echo "claims: unknown argument: $1" >&2
      exit 2
      ;;
  esac
done
case "$SCOPE" in
  all|unified|gpu) ;;
  *) echo "claims: unknown scope: $SCOPE" >&2; exit 2 ;;
esac
if [ -n "$SINCE" ] && [ ! -f "$SINCE" ]; then
  echo "claims: freshness sentinel not found: $SINCE" >&2
  exit 2
fi

SCANNER_HOST="$(uname -n) $(uname -sr)"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
JSONL="logs/claims.jsonl"
MD="docs/verified-today.generated.md"
mkdir -p logs docs

# claim id | gate log | required marker | scope
CLAIMS='
unified_adapter|logs/unified_adapter.log|UNIFIED_ADAPTER_PASS|unified
unified_cce_adapter|logs/unified_cce_adapter.log|UNIFIED_CCE_ADAPTER_PASS|unified
unified_oracle_adapter|logs/unified_oracle_adapter.log|ORACLE_CONTRACT_ADAPTER_PASS|unified
specialist_unit|logs/specialist_unit.log|SPECIALIST_UNIT_PASS|unified
specialist_health|logs/specialist_health.log|SPECIALIST_HEALTH_PASS|unified
unified_specialist_het_plan|logs/unified_specialist.log|HET_PLAN_PASS|unified
oracle_v2|logs/oracle_v2_test.log|ORACLE_V2_PASS|unified
async_runtime|logs/unified_async.log|ASYNC_RUNTIME_PASS|unified
async_gpu_lanes|logs/unified_gpu.log|ASYNC_GPU_LANES_PASS|gpu
qgkp_envelope|logs/qgkp_envelope_test.log|QGKP_ENVELOPE_PASS|unified
model_runtime|logs/unified_models_runtime.log|MODEL_RUNTIME_PASS|unified
model_catalog|logs/unified_models_catalog.log|MODEL_CATALOG_PASS|unified
ds4_dual_launcher|logs/unified_ds4_launcher.log|DS4_DUAL_LAUNCHER_PASS|unified
soul_host|logs/soul_host_test.log|SOUL_HOST_UNIFIED_PASS|unified
dotnet_host|logs/unified_host.log|CNET_HOST_UNIFIED_PASS|unified
'

: > "$JSONL"
if [ "$SCOPE" = all ] && [ -z "$SINCE" ]; then
  TITLE="Verified Evidence (generated)"
  PROVENANCE="This is an unscoped evidence inventory: PASS means the marker exists; log time is not current-run provenance."
else
  TITLE="Verified Today (generated)"
  PROVENANCE="Run-scoped evidence is fresh relative to the supplied sentinel."
fi
{
  echo "# $TITLE"
  echo
  echo "Generated by \`scripts/gen_claims.sh\` at $NOW on scanner \`$SCANNER_HOST\` (scope: \`$SCOPE\`)."
  echo "$PROVENANCE"
  echo "Do not edit; regenerate. FAIL/MISSING/STALE outranks any prose claim."
  echo
  echo "| Claim | Scope | Gate log | Marker | Verdict | Log mtime (UTC) |"
  echo "|---|---|---|---|---|---|"
} > "$MD"

total=0
passed=0
out_of_scope=0
bad=0
while IFS='|' read -r id log marker claim_scope; do
  [ -z "$id" ] && continue
  ts="-"
  if [ -f "$log" ]; then
    ts="$(date -u -r "$log" +%Y-%m-%dT%H:%M:%SZ)"
  fi

  if [ "$SCOPE" != all ] && [ "$claim_scope" != "$SCOPE" ]; then
    verdict="OUT_OF_SCOPE"
    out_of_scope=$((out_of_scope + 1))
  else
    total=$((total + 1))
    if [ ! -f "$log" ]; then
      verdict="MISSING"
      bad=$((bad + 1))
    elif [ -n "$SINCE" ] && [ "$SINCE" -nt "$log" ]; then
      verdict="STALE"
      bad=$((bad + 1))
    elif awk -v marker="$marker" '$1 == marker { found = 1 } END { exit !found }' "$log"; then
      verdict="PASS"
      passed=$((passed + 1))
    else
      verdict="FAIL"
      bad=$((bad + 1))
    fi
  fi

  printf '{"claim":"%s","scope":"%s","gate_log":"%s","marker":"%s","verdict":"%s","log_mtime_utc":"%s","generated_utc":"%s","scanner_host":"%s"}\n' \
    "$id" "$claim_scope" "$log" "$marker" "$verdict" "$ts" "$NOW" "$SCANNER_HOST" >> "$JSONL"
  printf '| %s | %s | `%s` | `%s` | %s | %s |\n' \
    "$id" "$claim_scope" "$log" "$marker" "$verdict" "$ts" >> "$MD"
done <<EOF
$CLAIMS
EOF

{
  echo
  if [ "$SCOPE" = all ]; then
    echo "**$passed/$total claims verified.**"
  else
    echo "**$passed/$total in-scope claims verified; $out_of_scope out of scope.**"
  fi
  echo "MISSING means evidence is absent; STALE means it predates the run sentinel."
} >> "$MD"

echo "claims: $passed/$total verified, $out_of_scope out of scope -> $JSONL, $MD"
if [ "$STRICT" -eq 1 ] && [ "$bad" -ne 0 ]; then
  exit 1
fi
