#!/usr/bin/env python3
"""Generate C + .NET alphabets from config/json_toolcall_v0.json (single source)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "config" / "json_toolcall_v0.json"
C_OUT = ROOT / "include" / "json_toolcall_alphabet.inc"
CS_OUT = ROOT / "dotnet" / "Cce" / "JsonToolCall.Alphabet.g.cs"


def c_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    tools = data["tools"]
    feats = data["features"]
    examples = data["examples"]
    assert len(tools) == len(examples), "tools/examples length mismatch"
    n_tool, n_feat = len(tools), len(feats)

    c_lines = [
        "/* AUTO-GENERATED by tools/gen_json_toolcall_alphabet.py — do not edit. */",
        f"#define CNET_JTC_N_TOOL_GEN {n_tool}",
        f"#define CNET_JTC_N_FEAT_GEN {n_feat}",
        f'static const char *const CNET_JTC_TOOLS_GEN[{n_tool}] = {{',
        ",\n".join(f"    {c_string(t)}" for t in tools),
        "};",
        f"static const char *const CNET_JTC_FEATS_GEN[{n_feat}] = {{",
        ",\n".join(f"    {c_string(f)}" for f in feats),
        "};",
        f"static const char *const CNET_JTC_EXAMPLES_GEN[{n_tool}] = {{",
        ",\n".join(f"    {c_string(e)}" for e in examples),
        "};",
        "",
    ]
    C_OUT.write_text("\n".join(c_lines), encoding="utf-8")

    cs_tools = ",\n        ".join(c_string(t) for t in tools)
    cs_feats = ",\n        ".join(c_string(f) for f in feats)
    cs_ex = ",\n        ".join(c_string(e) for e in examples)
    cs = f"""// <auto-generated />
// Generated by tools/gen_json_toolcall_alphabet.py from config/json_toolcall_v0.json
// Do not edit by hand.
namespace CNET.Cce;

public static partial class JsonToolCall
{{
    public const int FeatureCountGen = {n_feat};
    public const int ToolCountGen = {n_tool};
    public const string UnitNameGen = {c_string(data["unit_name"])};
    public const string InputTagGen = {c_string(data["input_tag"])};
    public const string GoalTagGen = {c_string(data["goal_tag"])};

    private static readonly string[] ToolNamesGen =
    {{
        {cs_tools}
    }};

    private static readonly string[] FeatureNamesGen =
    {{
        {cs_feats}
    }};

    private static readonly string[] ExampleJsonGen =
    {{
        {cs_ex}
    }};
}}
"""
    CS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CS_OUT.write_text(cs, encoding="utf-8")
    print(f"wrote {C_OUT.relative_to(ROOT)}")
    print(f"wrote {CS_OUT.relative_to(ROOT)}")
    print("JSON_TOOLCALL_ALPHABET_GEN_OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
