<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CNET.Llm.Core\CNET.Llm.Core.csproj" />
    <ProjectReference Include="..\..\src\CNET.Llm.Models\CNET.Llm.Models.csproj" />
    <ProjectReference Include="..\..\src\CNET.Llm.Cpu\CNET.Llm.Cpu.csproj" />
    <ProjectReference Include="..\..\src\CNET.Llm.Cuda\CNET.Llm.Cuda.csproj" />
    <ProjectReference Include="..\..\src\CNET.Llm.Engine\CNET.Llm.Engine.csproj" />
    <ProjectReference Include="..\..\src\CNET.Llm.HuggingFace\CNET.Llm.HuggingFace.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
